// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        javaSourceCompatibility = JavaVersion.VERSION_17
        javaTargetCompatibility = JavaVersion.VERSION_17

        androidApplicationMinSdkVersion = 24 // Android 7.0 (Nougat) - Not supported
        androidApplicationTargetSdkVersion = 28 // Android 9 (Pie) - Not supported

        androidApplicationCompileSdkVersion = 35 // Android 15 [Supports Java 17] - Current version as on 2024-09-26

        artifactsDirectory = "$rootDir/artifacts/"

        androidApplicationVersionCode = 8
        androidApplicationVersionName = "1.0.7"
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Use this chunk to enable detailed massages about deprecated APIs
gradle.projectsEvaluated {
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.compilerArgs << "-Xlint:deprecation"
        }
    }
}
